### ISSUE TITLE
Headers

### ISSUE THREAD

**Issue by visch** [ikogan/rundeck-http-plugin#3]
Adding customer headers would be sweet. I'd like to be able to define a header called apiKey. If I need this to work I"ll get a PR in otherwise I"ll probably just use curl for now.

**Comment by ikogan** [comment]
Hey, thank you for your suggestion! Unfortunately we aren't able to maintain the project anymore.

**Comment by visch** [comment]
Thanks for the heads up @ikogan 

Thanks @ltamaster for fixing this in the rundeck fork
