### ISSUE TITLE
SSH handshake failure

### ISSUE THREAD

**Issue by jerome83136** [ikogan/rundeck-http-plugin#6]
Hi,
I got an SSL handshake failure while using this plugin to make an HTTP GET on a https URL

I have tried with the option "Validate SSL Certificates" checked and unchecked --> same result

I have tried to add the CA certificate of the HTTPS entrypoint I'm targeting, into the Rundeck's truststore and it didn't work.

I think the option "Validate SSL Certificates" does'nt work.

Also, I think the rundeck-http-plugin shlould use the JVM's default truststore. Is it already what it is supposed to do ?
It seems it does not work.

Thanks for your help
Best regards

**Comment by ikogan** [comment]
Hi, I'm sorry about your issue and that it hasn't gotten any attention. I'm not sure whether or not the "Validate Certificates" option is working anymore, the relevant code is here: https://github.com/ohioit/rundeck-http-plugin/blob/c97154ffae2700b6042fae120899acbe4a69aa61/src/main/java/edu/ohio/ais/rundeck/HttpWorkflowStepPlugin.java#L163.

The plugin should do whatever `org.apache.http.client.HttpClient` does. One thing I would check is to make sure that your SSL configuration is _otherwise_ valid besides the invalid certificate. For example: you're not using out of date (and likely compromised) ciphers.

Unfortunately, we've stopped using Rundeck so can't really work directly on this issue. Sorry about that.
